name: libusb
description: Dart wrapper via `dart:ffi` for https://github.com/libusb/libusb
version: 0.2.23+1
homepage: https://github.com/woodemi/libusb.dart

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  ffi: ^1.0.0
  convert: ^2.1.1

dev_dependencies:
  pedantic: ^1.9.0
  ffigen: ^1.2.0
  test: ^1.15.7

ffigen:
  name: Libusb
  description: Bindings to `libusb.h`.
  output: 'lib/libusb.dart'
  headers:
    entry-points:
      - 'libusb-1.0/libusb.h'
    include-directives: # include only these header files and necessary structs from other header files
      - '**libusb.h'
